config/routes.rb
Rails.application.routes.draw do
  

  devise_for :models, :path_names => { :sign_in => "register"}
  resources :books do
    collection {post :import}
  end
  root :to => "books#new"

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
	belongs_to :model
end

app/models/book.rb
class Book < ActiveRecord::Base
	validates :name, presence: true
	validates :password, presence: true

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |book|
				csv << book.attributes.values_at(*column_names)
			end
		end	
	end

	#def self.import(file)
	#	CSV.foreach(file.path, headers: true) do |row|
	#		Book.create! row.to_hash
	#	end
	#end

end
	

app/models/model.rb
class Model < ActiveRecord::Base
	has_many :authentications
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

       
         
end

app/controllers/application_controller.rb
	class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def index
  	@authentications = Authentication.all
  end

  def create
  	reder :text => request.env["rack.auth"].inspect
  end

  def destroy
  	@authentication = Authentication.find(params[:id])
  	@authentication.destroy
  	redirect_to authentication_url
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_model!

	def show
	end
	
	def new
		@book = Book.new
	
	end

	def index
		@books =Book.all
		respond_to do |format|
			format.html
			format.csv { send_data text: @books.to_csv }
			format.xls #{ send_data text: @books.to_csv(col_sep: "\t") }
		end
	end
	

	def create
		@book = Book.create(params[:book].permit(:name, :password))
		@book.save
		render :text => 'successfull'
	end

	def import
		book.import(params[:file])
		redirect_to root_url, notice: "books imported."
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authentication/create.html.erb
<h1>Authentication#create</h1>
<p>Find me in app/views/authentication/create.html.erb</p>

app/views/authentication/destroy.html.erb
<h1>Authentication#destroy</h1>
<p>Find me in app/views/authentication/destroy.html.erb</p>

app/views/authentication/index.html.erb
<h1>Authentication#index</h1>
<p>Find me in app/views/authentication/index.html.erb</p>

app/views/books/_form.html.erb
<%= form_for @book, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                books_path, :class => 'btn' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.id, book_path(book) %></td>
        <td><%= book.name %></td>
        <td><%= book.password %></td>
        <td><%=l book.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_book_path(book), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      book_path(book),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_book_path,
            :class => 'btn btn-primary' %>

app/views/books/index.xls.erb
<table>
	<tr>
	<th>Name</th>
	<th>author</th>
</tr>
<% @books.each do |b| %>
<tr>
<td>
<%= b.name %></td><td>
<%= b.password %></td>
</tr>
<% end %>
</table>

app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
<%= link_to 'go to index', books_path%>

app/views/books/show.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @book.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @book.password %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              books_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_book_path(@book), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              book_path(@book),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<style>

</style>
  <title>Friend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	 <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<p>
<div id="container">
	<div id="model_nav">
		<H4>
		
		<% if model_signed_in? %>
		 signed in as <%= current_model.email %>.not you?
		 <%= link_to "signout", destroy_model_session_path, :method => :delete %>
		 
		 <% else %>
		 <%= link_to "sign up", new_model_registration_path %> or <%= link_to "sign in", new_model_session_path%>
		 <% end %>
		</H4>
		</div>
</p>
<p1>
    <a href="https://twitter.com/twitterapi" class="twitter-follow-button" data-show-count="false" data-lang="en">Follow twitter</a>

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</p1>
<div class="container">
	<div class="row">
		<div class="span9"><%= yield %></div>
		<div class="span3">
			<h3>About me </h3>This webpage is only for finditparts carrers, here i just wanted to show my abilities in developing a web page. It is just for reference please fell free to contact me at rxk31020@ucmo.edu
</div>



</body>
</html>